# Generated by Django 5.1.4 on 2025-01-06 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel_details',
            name='city',
            field=models.CharField(default='Unknown', max_length=100),
        ),
    ]
