# Generated by Django 5.1.4 on 2025-01-07 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_hotel_details_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel_details',
            name='guest_capacity',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='hotel_details',
            name='room_count',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hotel_details',
            name='city',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='hotel_details',
            name='image',
            field=models.ImageField(upload_to='hotel_images/'),
        ),
        migrations.AlterField(
            model_name='hotel_details',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='hotel_details',
            name='rating',
            field=models.DecimalField(decimal_places=1, max_digits=2),
        ),
    ]
